export default [
  {
    title: 'Pied Piper',
    subtitle: 'Senior Software Engineer',
    dateFrom: 'Sept 2017',
    dateTo: 'Present',
    roles: [
      'Writing components with React, LESS and PostCSS.',
      'Maintain consistency in design and layout with LESS theming.',
      'Managing data flow with Redux and Redux-thunk.',
      'Assist back end php developers in coding.',
    ],
    tools: [
      'PHP',
      'MySQL',
      'React',
      'Redux',
      'LESS',
      'ReducSaga',
    ],
  },
  {
    title: 'Company',
    subtitle: 'Front End Developer',
    dateFrom: 'Oct 2015',
    dateTo: 'Aug 2017',
    partTime: true,
    roles: [
      'Writing components with AngularJS, SASS and Typescript.',
      'Managing data flow with Flux and RxJS.',
    ],
    tools: [
      'AngularJS',
      'Typescript',
      'Flux',
      'RxJS',
      'SASS',
    ],
  },
  {
    title: 'Company',
    subtitle: 'Full Stack Developer',
    dateFrom: 'Sept 2014',
    dateTo: 'May 2017',
    roles: [
      'Designed and implemented data storage solutions with MongoDB',
      'Building RESTful APIs with NodeJS and Express',
      'Writing re-usable components with React and styled-components.',
      'Managing data flow with Redux and Redux-saga',
    ],
    tools: [
      'React',
      'Redux',
      'ReduxSaga',
      'NodeJS',
      'MongoDB',
      'Typescript',
    ],
  },
];
