export default [
  {
    title: "Wai-Techs, Egypt",
    subtitle: "Senior Software Engineer",
    dateFrom: "Jan. 2020",
    dateTo: "Current",
    roles: [
      "Designing a scalable database and RESTful API services.",
      "Discussing technical requirements for integration with front-end developers.",
      "Managing hosting environments and CI/CD pipelines.",
      "Monitoring backend logs.",
      "Writing Scripts for different application tasks.",
      "API documentation.",
      "QA testing assistance.",
    ],
    tools: [
      "AWS",
      "Terraform",
      "GitHub Actions",
      "Python",
      "Django",
      "MariaDB",
      "InfluxDB",
      "Docker",
      "ReactJS",
    ],
  },
  {
    title: "OriginPush, Egypt",
    subtitle: "Backend Engineer",
    dateFrom: "Aug. 2017",
    dateTo: "Dec. 2019",
    roles: [
      "Defining and communicating technical and design requirements.",
      "Creating admin dashboards.",
      "Designing and implementing RESTful API services.",
      "Creating lambda functions to handle different SNS/SQS events.",
    ],
    tools: [
      "Spring Boot",
      "Hibernate",
      "MySQL",
      "Swagger",
      "NodeJS",
      "Docker",
      "AWS",
      "Terraform",
      "Jenkins",
    ],
  },
  {
    title: "Freelancing projects: Black-crows, Goodsense",
    subtitle: "NodeJS Backend Engineer",
    dateFrom: "Oct. 2014",
    dateTo: "July. 2017",
    roles: [
      "Designing ERD and database schema.",
      "Building RESTful APIs with a cache layer.",
      "Deploying NodeJS backend on Heroku.",
    ],
    tools: ["NodeJS", "Redis", "MonogoDB", "Heroku"],
  },
];
