export default [
  {
    title: "Auto1 Group",
    subtitle: "Principal Software Engineer",
    dateFrom: "Jan 2021",
    dateTo: "Present",
    roles: [
      "Designing micro-frontend infrastructure solutions.",
      "Implementing CI/CD for micro-frontend solutions (AWS, Jenkins).",
      "Implementing BFF layers (NodeJS, AWS, Jenkins).",
      "Signoffs for frontend solution designs.",
      "Leading different teams to deliver bussiness requirements.",
      "Contributing in the micro-services infrastructure decisions.",
    ],
    tools: ["AWS", "Terraform", "Jenkins", "Groovy"],
  },
  {
    title: "Auto1 Group",
    subtitle: "Expert Software Engineer",
    dateFrom: "Jan 2019",
    dateTo: "Dec 2020",
    roles: [],
    tools: [],
  },
  {
    title: "Auto1 Group",
    subtitle: "Senior Software Engineer",
    dateFrom: "Sept 2017",
    dateTo: "Dec 2018",
    roles: [],
    tools: [],
  },
  {
    title: "Goodsense / Blackcrows",
    subtitle: "Lead Software Engineer",
    dateFrom: "Aug 2014",
    dateTo: "Aug 2017",
    roles: [
      "Designed and implemented data storage solutions with MongoDB",
      "Building RESTful APIs with NodeJS and Express",
      "Writing re-usable components with React and styled-components.",
      "Managing data flow with Redux and Redux-saga",
    ],
    tools: ["React", "Redux", "NodeJS", "MongoDB"],
  },
];
